import './globals.css';
import Footer from './Components/Footer';
import Navbar from '@/app/Components/Navbar';
export const metadata = {
  title: 'PIAIC ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><Navbar/>{children}<Footer/>
      </body>
    </html>
  )
}
